#!/bin/bash

cd /srv/pow_demo

case $NODENAME in
a@127.0.0.1)
  if [ ! -f setup-done ]; then
    touch setup-done

    # Install assets
    (
    cd /srv/pow_demo/assets
    npm install || (chown -R root:root node_modules && npm install)
    )

    # Always install mix dependencies
    (cd /srv/pow_demo && mix deps.get)

    # Try to create the database if it doesn't exist yet
    createdb -h postgres -U postgres my_app_dev && mix ecto.setup
  fi
  ;;
b@127.0.0.1)
  # Wait for the first node to initialize

  echo "Waiting for a@127.0.0.1"

  until wget -qO /dev/null app_1:4000; do
    echo -n "."
    sleep 2
  done

  ;;
esac

# Run the application
elixir --cookie test --name $NODENAME -S mix phx.server
